[build-system]
requires = ["setuptools",
            "wheel",
            "numpy; python_version=='2.7'",
	    "oldest-supported-numpy; python_version >='3.0' and python_version <'3.9'",
            "numpy>=2; python_version>='3.9'"]


build-backend = "setuptools.build_meta"
