/* File: connectedpixelsmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Fri Sep 22 14:22:39 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *connectedpixels_error;
static PyObject *connectedpixels_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = connectedpixels_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = connectedpixels_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/
  /* start usercode multiline (0) */

#include "blobs.h"
   
  /* end multiline (0)*/

/* See f2py2e/rules.py */
extern int connectedpixels(float*,int*,float,int,int,int,int);
extern void blobproperties(float*,int*,int,float,int,int,int,double*);
extern void blob_moments(double*,int);
extern int bloboverlaps(int*,int,double*,int*,int,double*,int,int,int);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/****************************** connectedpixels ******************************/
static char doc_f2py_rout_connectedpixels_connectedpixels[] = "\
connectedpixels = connectedpixels(data,labels,threshold,[verbose,con8])\n\nWrapper for ``connectedpixels``.\
\n\nParameters\n----------\n"
"data : input rank-2 array('f') with bounds (ns,nf)\n"
"labels : in/output rank-2 array('i') with bounds (ns,nf)\n"
"threshold : input float\n"
"\nOther Parameters\n----------------\n"
"verbose : input int, optional\n    Default: 0\n"
"con8 : input int, optional\n    Default: 1\n"
"\nReturns\n-------\n"
"connectedpixels : int";
/* extern int connectedpixels(float*,int*,float,int,int,int,int); */
static PyObject *f2py_rout_connectedpixels_connectedpixels(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(float*,int*,float,int,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int connectedpixels_return_value=0;
  float *data = NULL;
  npy_intp data_Dims[2] = {-1, -1};
  const int data_Rank = 2;
  PyArrayObject *capi_data_tmp = NULL;
  int capi_data_intent = 0;
  PyObject *data_capi = Py_None;
  int *labels = NULL;
  npy_intp labels_Dims[2] = {-1, -1};
  const int labels_Rank = 2;
  PyArrayObject *capi_labels_tmp = NULL;
  int capi_labels_intent = 0;
  PyObject *labels_capi = Py_None;
  float threshold = 0;
  PyObject *threshold_capi = Py_None;
  int verbose = 0;
  PyObject *verbose_capi = Py_None;
  int con8 = 0;
  PyObject *con8_capi = Py_None;
  int ns = 0;
  int nf = 0;
  static char *capi_kwlist[] = {"data","labels","threshold","verbose","con8",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OO:connectedpixels.connectedpixels",\
    capi_kwlist,&data_capi,&labels_capi,&threshold_capi,&verbose_capi,&con8_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable verbose */
  if (verbose_capi == Py_None) verbose = 0; else
    f2py_success = int_from_pyobj(&verbose,verbose_capi,"connectedpixels.connectedpixels() 1st keyword (verbose) can't be converted to int");
  if (f2py_success) {
  /* Processing variable con8 */
  if (con8_capi == Py_None) con8 = 1; else
    f2py_success = int_from_pyobj(&con8,con8_capi,"connectedpixels.connectedpixels() 2nd keyword (con8) can't be converted to int");
  if (f2py_success) {
  /* Processing variable threshold */
    f2py_success = float_from_pyobj(&threshold,threshold_capi,"connectedpixels.connectedpixels() 3rd argument (threshold) can't be converted to float");
  if (f2py_success) {
  /* Processing variable data */
  ;
  capi_data_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_data_tmp = array_from_pyobj(NPY_FLOAT,data_Dims,data_Rank,capi_data_intent,data_capi);
  if (capi_data_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `data' of connectedpixels.connectedpixels to C/Fortran array" );
  } else {
    data = (float *)(PyArray_DATA(capi_data_tmp));

  /* Processing variable nf */
  nf = shape(data,1);
  /* Processing variable ns */
  ns = shape(data,0);
  /* Processing variable labels */
  labels_Dims[0]=ns,labels_Dims[1]=nf;
  capi_labels_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_labels_tmp = array_from_pyobj(NPY_INT,labels_Dims,labels_Rank,capi_labels_intent,labels_capi);
  if (capi_labels_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `labels' of connectedpixels.connectedpixels to C/Fortran array" );
  } else {
    labels = (int *)(PyArray_DATA(capi_labels_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  Py_BEGIN_ALLOW_THREADS
  connectedpixels_return_value = (*f2py_func)(data,labels,threshold,verbose,con8,ns,nf);
  Py_END_ALLOW_THREADS
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",connectedpixels_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_labels_tmp!=labels_capi) {
    Py_XDECREF(capi_labels_tmp); }
  }  /*if (capi_labels_tmp == NULL) ... else of labels*/
  /* End of cleaning variable labels */
  /* End of cleaning variable ns */
  /* End of cleaning variable nf */
  if((PyObject *)capi_data_tmp!=data_capi) {
    Py_XDECREF(capi_data_tmp); }
  }  /*if (capi_data_tmp == NULL) ... else of data*/
  /* End of cleaning variable data */
  } /*if (f2py_success) of threshold*/
  /* End of cleaning variable threshold */
  } /*if (f2py_success) of con8*/
  /* End of cleaning variable con8 */
  } /*if (f2py_success) of verbose*/
  /* End of cleaning variable verbose */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of connectedpixels ***************************/

/******************************* blobproperties *******************************/
static char doc_f2py_rout_connectedpixels_blobproperties[] = "\
results = blobproperties(data,labels,np,[omega,verbose])\n\nWrapper for ``blobproperties``.\
\n\nParameters\n----------\n"
"data : input rank-2 array('f') with bounds (ns,nf)\n"
"labels : input rank-2 array('i') with bounds (ns,nf)\n"
"np : input int\n"
"\nOther Parameters\n----------------\n"
"omega : input float, optional\n    Default: 0\n"
"verbose : input int, optional\n    Default: 0\n"
"\nReturns\n-------\n"
"results : rank-2 array('d') with bounds (np,(NPROPERTY))";
/* extern void blobproperties(float*,int*,int,float,int,int,int,double*); */
static PyObject *f2py_rout_connectedpixels_blobproperties(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*,int,float,int,int,int,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *data = NULL;
  npy_intp data_Dims[2] = {-1, -1};
  const int data_Rank = 2;
  PyArrayObject *capi_data_tmp = NULL;
  int capi_data_intent = 0;
  PyObject *data_capi = Py_None;
  int *labels = NULL;
  npy_intp labels_Dims[2] = {-1, -1};
  const int labels_Rank = 2;
  PyArrayObject *capi_labels_tmp = NULL;
  int capi_labels_intent = 0;
  PyObject *labels_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  float omega = 0;
  PyObject *omega_capi = Py_None;
  int verbose = 0;
  PyObject *verbose_capi = Py_None;
  int ns = 0;
  int nf = 0;
  double *results = NULL;
  npy_intp results_Dims[2] = {-1, -1};
  const int results_Rank = 2;
  PyArrayObject *capi_results_tmp = NULL;
  int capi_results_intent = 0;
  static char *capi_kwlist[] = {"data","labels","np","omega","verbose",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OO:connectedpixels.blobproperties",\
    capi_kwlist,&data_capi,&labels_capi,&np_capi,&omega_capi,&verbose_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable verbose */
  if (verbose_capi == Py_None) verbose = 0; else
    f2py_success = int_from_pyobj(&verbose,verbose_capi,"connectedpixels.blobproperties() 2nd keyword (verbose) can't be converted to int");
  if (f2py_success) {
  /* Processing variable data */
  ;
  capi_data_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_data_tmp = array_from_pyobj(NPY_FLOAT,data_Dims,data_Rank,capi_data_intent,data_capi);
  if (capi_data_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `data' of connectedpixels.blobproperties to C/Fortran array" );
  } else {
    data = (float *)(PyArray_DATA(capi_data_tmp));

  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"connectedpixels.blobproperties() 3rd argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable omega */
  if (omega_capi == Py_None) omega = 0; else
    f2py_success = float_from_pyobj(&omega,omega_capi,"connectedpixels.blobproperties() 1st keyword (omega) can't be converted to float");
  if (f2py_success) {
  /* Processing variable results */
  results_Dims[0]=np,results_Dims[1]=(NPROPERTY);
  capi_results_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE|F2PY_INTENT_C;
  capi_results_tmp = array_from_pyobj(NPY_DOUBLE,results_Dims,results_Rank,capi_results_intent,Py_None);
  if (capi_results_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting hidden `results' of connectedpixels.blobproperties to C/Fortran array" );
  } else {
    results = (double *)(PyArray_DATA(capi_results_tmp));

  /* Processing variable nf */
  nf = shape(data,1);
  /* Processing variable ns */
  ns = shape(data,0);
  /* Processing variable labels */
  labels_Dims[0]=ns,labels_Dims[1]=nf;
  capi_labels_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_labels_tmp = array_from_pyobj(NPY_INT,labels_Dims,labels_Rank,capi_labels_intent,labels_capi);
  if (capi_labels_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `labels' of connectedpixels.blobproperties to C/Fortran array" );
  } else {
    labels = (int *)(PyArray_DATA(capi_labels_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
      Py_BEGIN_ALLOW_THREADS
        (*f2py_func)(data,labels,np,omega,verbose,ns,nf,results);
      Py_END_ALLOW_THREADS
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_results_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_labels_tmp!=labels_capi) {
    Py_XDECREF(capi_labels_tmp); }
  }  /*if (capi_labels_tmp == NULL) ... else of labels*/
  /* End of cleaning variable labels */
  /* End of cleaning variable ns */
  /* End of cleaning variable nf */
  }  /*if (capi_results_tmp == NULL) ... else of results*/
  /* End of cleaning variable results */
  } /*if (f2py_success) of omega*/
  /* End of cleaning variable omega */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_data_tmp!=data_capi) {
    Py_XDECREF(capi_data_tmp); }
  }  /*if (capi_data_tmp == NULL) ... else of data*/
  /* End of cleaning variable data */
  } /*if (f2py_success) of verbose*/
  /* End of cleaning variable verbose */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of blobproperties ***************************/

/******************************** blob_moments ********************************/
static char doc_f2py_rout_connectedpixels_blob_moments[] = "\
blob_moments(results)\n\nWrapper for ``blob_moments``.\
\n\nParameters\n----------\n"
"results : in/output rank-2 array('d') with bounds (np,(NPROPERTY))";
/* extern void blob_moments(double*,int); */
static PyObject *f2py_rout_connectedpixels_blob_moments(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *results = NULL;
  npy_intp results_Dims[2] = {-1, -1};
  const int results_Rank = 2;
  PyArrayObject *capi_results_tmp = NULL;
  int capi_results_intent = 0;
  PyObject *results_capi = Py_None;
  int np = 0;
  static char *capi_kwlist[] = {"results",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:connectedpixels.blob_moments",\
    capi_kwlist,&results_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable results */
  results_Dims[1]=(NPROPERTY);
  capi_results_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_results_tmp = array_from_pyobj(NPY_DOUBLE,results_Dims,results_Rank,capi_results_intent,results_capi);
  if (capi_results_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `results' of connectedpixels.blob_moments to C/Fortran array" );
  } else {
    results = (double *)(PyArray_DATA(capi_results_tmp));

  /* Processing variable np */
  np = shape(results,0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
      Py_BEGIN_ALLOW_THREADS
        (*f2py_func)(results,np);
      Py_END_ALLOW_THREADS
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable np */
  if((PyObject *)capi_results_tmp!=results_capi) {
    Py_XDECREF(capi_results_tmp); }
  }  /*if (capi_results_tmp == NULL) ... else of results*/
  /* End of cleaning variable results */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of blob_moments ****************************/

/******************************** bloboverlaps ********************************/
static char doc_f2py_rout_connectedpixels_bloboverlaps[] = "\
bloboverlaps = bloboverlaps(labels1,npk1,results1,labels2,npk2,results2,[verbose])\n\nWrapper for ``bloboverlaps``.\
\n\nParameters\n----------\n"
"labels1 : in/output rank-2 array('i') with bounds (ns,nf)\n"
"npk1 : input int\n"
"results1 : in/output rank-2 array('d') with bounds (:,(NPROPERTY))\n"
"labels2 : in/output rank-2 array('i') with bounds (ns,nf)\n"
"npk2 : input int\n"
"results2 : in/output rank-2 array('d') with bounds (:,(NPROPERTY))\n"
"\nOther Parameters\n----------------\n"
"verbose : input int, optional\n    Default: 0\n"
"\nReturns\n-------\n"
"bloboverlaps : int";
/* extern int bloboverlaps(int*,int,double*,int*,int,double*,int,int,int); */
static PyObject *f2py_rout_connectedpixels_bloboverlaps(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(int*,int,double*,int*,int,double*,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int bloboverlaps_return_value=0;
  int *labels1 = NULL;
  npy_intp labels1_Dims[2] = {-1, -1};
  const int labels1_Rank = 2;
  PyArrayObject *capi_labels1_tmp = NULL;
  int capi_labels1_intent = 0;
  PyObject *labels1_capi = Py_None;
  int npk1 = 0;
  PyObject *npk1_capi = Py_None;
  double *results1 = NULL;
  npy_intp results1_Dims[2] = {-1, -1};
  const int results1_Rank = 2;
  PyArrayObject *capi_results1_tmp = NULL;
  int capi_results1_intent = 0;
  PyObject *results1_capi = Py_None;
  int *labels2 = NULL;
  npy_intp labels2_Dims[2] = {-1, -1};
  const int labels2_Rank = 2;
  PyArrayObject *capi_labels2_tmp = NULL;
  int capi_labels2_intent = 0;
  PyObject *labels2_capi = Py_None;
  int npk2 = 0;
  PyObject *npk2_capi = Py_None;
  double *results2 = NULL;
  npy_intp results2_Dims[2] = {-1, -1};
  const int results2_Rank = 2;
  PyArrayObject *capi_results2_tmp = NULL;
  int capi_results2_intent = 0;
  PyObject *results2_capi = Py_None;
  int verbose = 0;
  PyObject *verbose_capi = Py_None;
  int ns = 0;
  int nf = 0;
  static char *capi_kwlist[] = {"labels1","npk1","results1","labels2","npk2","results2","verbose",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|O:connectedpixels.bloboverlaps",\
    capi_kwlist,&labels1_capi,&npk1_capi,&results1_capi,&labels2_capi,&npk2_capi,&results2_capi,&verbose_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable results2 */
  results2_Dims[1]=(NPROPERTY);
  capi_results2_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_results2_tmp = array_from_pyobj(NPY_DOUBLE,results2_Dims,results2_Rank,capi_results2_intent,results2_capi);
  if (capi_results2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 6th argument `results2' of connectedpixels.bloboverlaps to C/Fortran array" );
  } else {
    results2 = (double *)(PyArray_DATA(capi_results2_tmp));

  /* Processing variable verbose */
  if (verbose_capi == Py_None) verbose = 0; else
    f2py_success = int_from_pyobj(&verbose,verbose_capi,"connectedpixels.bloboverlaps() 1st keyword (verbose) can't be converted to int");
  if (f2py_success) {
  /* Processing variable results1 */
  results1_Dims[1]=(NPROPERTY);
  capi_results1_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_results1_tmp = array_from_pyobj(NPY_DOUBLE,results1_Dims,results1_Rank,capi_results1_intent,results1_capi);
  if (capi_results1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 3rd argument `results1' of connectedpixels.bloboverlaps to C/Fortran array" );
  } else {
    results1 = (double *)(PyArray_DATA(capi_results1_tmp));

  /* Processing variable labels1 */
  ;
  capi_labels1_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_labels1_tmp = array_from_pyobj(NPY_INT,labels1_Dims,labels1_Rank,capi_labels1_intent,labels1_capi);
  if (capi_labels1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `labels1' of connectedpixels.bloboverlaps to C/Fortran array" );
  } else {
    labels1 = (int *)(PyArray_DATA(capi_labels1_tmp));

  /* Processing variable npk2 */
    f2py_success = int_from_pyobj(&npk2,npk2_capi,"connectedpixels.bloboverlaps() 5th argument (npk2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable npk1 */
    f2py_success = int_from_pyobj(&npk1,npk1_capi,"connectedpixels.bloboverlaps() 2nd argument (npk1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nf */
  nf = shape(labels1,1);
  /* Processing variable ns */
  ns = shape(labels1,0);
  /* Processing variable labels2 */
  labels2_Dims[0]=ns,labels2_Dims[1]=nf;
  capi_labels2_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_labels2_tmp = array_from_pyobj(NPY_INT,labels2_Dims,labels2_Rank,capi_labels2_intent,labels2_capi);
  if (capi_labels2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 4th argument `labels2' of connectedpixels.bloboverlaps to C/Fortran array" );
  } else {
    labels2 = (int *)(PyArray_DATA(capi_labels2_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  bloboverlaps_return_value = (*f2py_func)(labels1,npk1,results1,labels2,npk2,results2,verbose,ns,nf);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",bloboverlaps_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_labels2_tmp!=labels2_capi) {
    Py_XDECREF(capi_labels2_tmp); }
  }  /*if (capi_labels2_tmp == NULL) ... else of labels2*/
  /* End of cleaning variable labels2 */
  /* End of cleaning variable ns */
  /* End of cleaning variable nf */
  } /*if (f2py_success) of npk1*/
  /* End of cleaning variable npk1 */
  } /*if (f2py_success) of npk2*/
  /* End of cleaning variable npk2 */
  if((PyObject *)capi_labels1_tmp!=labels1_capi) {
    Py_XDECREF(capi_labels1_tmp); }
  }  /*if (capi_labels1_tmp == NULL) ... else of labels1*/
  /* End of cleaning variable labels1 */
  if((PyObject *)capi_results1_tmp!=results1_capi) {
    Py_XDECREF(capi_results1_tmp); }
  }  /*if (capi_results1_tmp == NULL) ... else of results1*/
  /* End of cleaning variable results1 */
  } /*if (f2py_success) of verbose*/
  /* End of cleaning variable verbose */
  if((PyObject *)capi_results2_tmp!=results2_capi) {
    Py_XDECREF(capi_results2_tmp); }
  }  /*if (capi_results2_tmp == NULL) ... else of results2*/
  /* End of cleaning variable results2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of bloboverlaps ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"connectedpixels",-1,{{-1}},0,(char *)connectedpixels,(f2py_init_func)f2py_rout_connectedpixels_connectedpixels,doc_f2py_rout_connectedpixels_connectedpixels},
  {"blobproperties",-1,{{-1}},0,(char *)blobproperties,(f2py_init_func)f2py_rout_connectedpixels_blobproperties,doc_f2py_rout_connectedpixels_blobproperties},
  {"blob_moments",-1,{{-1}},0,(char *)blob_moments,(f2py_init_func)f2py_rout_connectedpixels_blob_moments,doc_f2py_rout_connectedpixels_blob_moments},
  {"bloboverlaps",-1,{{-1}},0,(char *)bloboverlaps,(f2py_init_func)f2py_rout_connectedpixels_bloboverlaps,doc_f2py_rout_connectedpixels_bloboverlaps},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "connectedpixels",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_connectedpixels(void) {
#else
#define RETVAL
PyMODINIT_FUNC initconnectedpixels(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = connectedpixels_module = PyModule_Create(&moduledef);
#else
  m = connectedpixels_module = Py_InitModule("connectedpixels", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module connectedpixels (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'connectedpixels' is auto-generated with f2py (version:2).\nFunctions:\n"
"  connectedpixels = connectedpixels(data,labels,threshold,verbose=0,con8=1)\n"
"  results = blobproperties(data,labels,np,omega=0,verbose=0)\n"
"  blob_moments(results)\n"
"  bloboverlaps = bloboverlaps(labels1,npk1,results1,labels2,npk2,results2,verbose=0)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  connectedpixels_error = PyErr_NewException ("connectedpixels.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/
  /* start usercode multiline (0) */

#define str(x) (#x)
   PyDict_SetItemString(d,str(s_1)    ,PyInt_FromLong(s_1));
   PyDict_SetItemString(d,str(s_I)    ,PyInt_FromLong(s_I));
   PyDict_SetItemString(d,str(s_I2)   ,PyInt_FromLong(s_I2));
   PyDict_SetItemString(d,str(s_fI)   ,PyInt_FromLong(s_fI));
   PyDict_SetItemString(d,str(s_ffI)  ,PyInt_FromLong(s_ffI));
   PyDict_SetItemString(d,str(s_sI)   ,PyInt_FromLong(s_sI));
   PyDict_SetItemString(d,str(s_ssI)  ,PyInt_FromLong(s_ssI));
   PyDict_SetItemString(d,str(s_sfI)  ,PyInt_FromLong(s_sfI));
   PyDict_SetItemString(d,str(s_oI)   ,PyInt_FromLong(s_oI));
   PyDict_SetItemString(d,str(s_ooI)  ,PyInt_FromLong(s_ooI));
   PyDict_SetItemString(d,str(s_soI)  ,PyInt_FromLong(s_soI));
   PyDict_SetItemString(d,str(s_foI)  ,PyInt_FromLong(s_foI));
   PyDict_SetItemString(d,str(mx_I)   ,PyInt_FromLong(mx_I));
   PyDict_SetItemString(d,str(mx_I_f) ,PyInt_FromLong(mx_I_f));
   PyDict_SetItemString(d,str(mx_I_s) ,PyInt_FromLong(mx_I_s));
   PyDict_SetItemString(d,str(mx_I_o) ,PyInt_FromLong(mx_I_o));
   PyDict_SetItemString(d,str(bb_mx_f),PyInt_FromLong(bb_mx_f));
   PyDict_SetItemString(d,str(bb_mx_s),PyInt_FromLong(bb_mx_s));
   PyDict_SetItemString(d,str(bb_mx_o),PyInt_FromLong(bb_mx_o));
   PyDict_SetItemString(d,str(bb_mn_f),PyInt_FromLong(bb_mn_f));
   PyDict_SetItemString(d,str(bb_mn_s),PyInt_FromLong(bb_mn_s));
   PyDict_SetItemString(d,str(bb_mn_o),PyInt_FromLong(bb_mn_o));

   PyDict_SetItemString(d,str(avg_i),PyInt_FromLong(avg_i));
   PyDict_SetItemString(d,str(f_raw),PyInt_FromLong(f_raw));
   PyDict_SetItemString(d,str(s_raw),PyInt_FromLong(s_raw));
   PyDict_SetItemString(d,str(f_cen),PyInt_FromLong(f_cen));
   PyDict_SetItemString(d,str(s_cen),PyInt_FromLong(s_cen));
   PyDict_SetItemString(d,str(o_raw),PyInt_FromLong(o_raw));
   PyDict_SetItemString(d,str(m_ff),PyInt_FromLong(m_ff));
   PyDict_SetItemString(d,str(m_ss),PyInt_FromLong(m_ss));
   PyDict_SetItemString(d,str(m_oo),PyInt_FromLong(m_oo));
   PyDict_SetItemString(d,str(m_sf),PyInt_FromLong(m_sf));
   PyDict_SetItemString(d,str(m_so),PyInt_FromLong(m_so));
   PyDict_SetItemString(d,str(m_fo),PyInt_FromLong(m_fo));
   PyDict_SetItemString(d,str(dety),PyInt_FromLong(dety));
   PyDict_SetItemString(d,str(detz),PyInt_FromLong(detz));
   
   PyDict_SetItemString(d,str(NPROPERTY),PyInt_FromLong(NPROPERTY));

  /* end multiline (0)*/

#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"connectedpixels");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
