/* File: connectedpixelsmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Sep 26 13:42:58 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *connectedpixels_error;
static PyObject *connectedpixels_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
#ifdef _WIN32
typedef __int64 long_long;
#else
typedef long long long_long;
typedef unsigned long long unsigned_long_long;
#endif


/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(connectedpixels_error,errstring);\
    /*goto capi_fail;*/\
  } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = connectedpixels_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = connectedpixels_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/
  /* start usercode multiline (0) */

#include "blobs.h"
   
  /* end multiline (0)*/

/* See f2py2e/rules.py */
extern int connectedpixels(float*,int*,float,int,int,int,int);
extern void blobproperties(float*,int*,int,float,int,int,int,double*);
extern void blob_moments(double*,int);
extern int bloboverlaps(int*,int,double*,int*,int,double*,int,int,int);
extern void closest(double*,double*,int*,double*,int,int);
extern int score(double*,double*,double,int);
extern void score_and_refine(double*,double*,double,int*,double*,int);
extern int score_and_assign(double*,double*,double,double*,int*,int,int);
extern void refine_assigned(double*,double*,int*,int,int*,double*,int);
extern void put_incr(float*,long_long*,float*,int,int,int);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/****************************** connectedpixels ******************************/
static char doc_f2py_rout_connectedpixels_connectedpixels[] = "\
connectedpixels = connectedpixels(data,labels,threshold,[verbose,con8])\n\nWrapper for ``connectedpixels``.\
\n\nParameters\n----------\n"
"data : input rank-2 array('f') with bounds (ns,nf)\n"
"labels : in/output rank-2 array('i') with bounds (ns,nf)\n"
"threshold : input float\n"
"\nOther Parameters\n----------------\n"
"verbose : input int, optional\n    Default: 0\n"
"con8 : input int, optional\n    Default: 1\n"
"\nReturns\n-------\n"
"connectedpixels : int";
/* extern int connectedpixels(float*,int*,float,int,int,int,int); */
static PyObject *f2py_rout_connectedpixels_connectedpixels(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(float*,int*,float,int,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int connectedpixels_return_value=0;
  float *data = NULL;
  npy_intp data_Dims[2] = {-1, -1};
  const int data_Rank = 2;
  PyArrayObject *capi_data_tmp = NULL;
  int capi_data_intent = 0;
  PyObject *data_capi = Py_None;
  int *labels = NULL;
  npy_intp labels_Dims[2] = {-1, -1};
  const int labels_Rank = 2;
  PyArrayObject *capi_labels_tmp = NULL;
  int capi_labels_intent = 0;
  PyObject *labels_capi = Py_None;
  float threshold = 0;
  PyObject *threshold_capi = Py_None;
  int verbose = 0;
  PyObject *verbose_capi = Py_None;
  int con8 = 0;
  PyObject *con8_capi = Py_None;
  int ns = 0;
  int nf = 0;
  static char *capi_kwlist[] = {"data","labels","threshold","verbose","con8",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OO:connectedpixels.connectedpixels",\
    capi_kwlist,&data_capi,&labels_capi,&threshold_capi,&verbose_capi,&con8_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable verbose */
  if (verbose_capi == Py_None) verbose = 0; else
    f2py_success = int_from_pyobj(&verbose,verbose_capi,"connectedpixels.connectedpixels() 1st keyword (verbose) can't be converted to int");
  if (f2py_success) {
  /* Processing variable con8 */
  if (con8_capi == Py_None) con8 = 1; else
    f2py_success = int_from_pyobj(&con8,con8_capi,"connectedpixels.connectedpixels() 2nd keyword (con8) can't be converted to int");
  if (f2py_success) {
  /* Processing variable threshold */
    f2py_success = float_from_pyobj(&threshold,threshold_capi,"connectedpixels.connectedpixels() 3rd argument (threshold) can't be converted to float");
  if (f2py_success) {
  /* Processing variable data */
  ;
  capi_data_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_data_tmp = array_from_pyobj(NPY_FLOAT,data_Dims,data_Rank,capi_data_intent,data_capi);
  if (capi_data_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `data' of connectedpixels.connectedpixels to C/Fortran array" );
  } else {
    data = (float *)(PyArray_DATA(capi_data_tmp));

  /* Processing variable nf */
  nf = shape(data,1);
  /* Processing variable ns */
  ns = shape(data,0);
  /* Processing variable labels */
  labels_Dims[0]=ns,labels_Dims[1]=nf;
  capi_labels_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_labels_tmp = array_from_pyobj(NPY_INT,labels_Dims,labels_Rank,capi_labels_intent,labels_capi);
  if (capi_labels_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `labels' of connectedpixels.connectedpixels to C/Fortran array" );
  } else {
    labels = (int *)(PyArray_DATA(capi_labels_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  Py_BEGIN_ALLOW_THREADS
  connectedpixels_return_value = (*f2py_func)(data,labels,threshold,verbose,con8,ns,nf);
  Py_END_ALLOW_THREADS
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",connectedpixels_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_labels_tmp!=labels_capi) {
    Py_XDECREF(capi_labels_tmp); }
  }  /*if (capi_labels_tmp == NULL) ... else of labels*/
  /* End of cleaning variable labels */
  /* End of cleaning variable ns */
  /* End of cleaning variable nf */
  if((PyObject *)capi_data_tmp!=data_capi) {
    Py_XDECREF(capi_data_tmp); }
  }  /*if (capi_data_tmp == NULL) ... else of data*/
  /* End of cleaning variable data */
  } /*if (f2py_success) of threshold*/
  /* End of cleaning variable threshold */
  } /*if (f2py_success) of con8*/
  /* End of cleaning variable con8 */
  } /*if (f2py_success) of verbose*/
  /* End of cleaning variable verbose */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of connectedpixels ***************************/

/******************************* blobproperties *******************************/
static char doc_f2py_rout_connectedpixels_blobproperties[] = "\
results = blobproperties(data,labels,np,[omega,verbose])\n\nWrapper for ``blobproperties``.\
\n\nParameters\n----------\n"
"data : input rank-2 array('f') with bounds (ns,nf)\n"
"labels : input rank-2 array('i') with bounds (ns,nf)\n"
"np : input int\n"
"\nOther Parameters\n----------------\n"
"omega : input float, optional\n    Default: 0\n"
"verbose : input int, optional\n    Default: 0\n"
"\nReturns\n-------\n"
"results : rank-2 array('d') with bounds (np,(NPROPERTY))";
/* extern void blobproperties(float*,int*,int,float,int,int,int,double*); */
static PyObject *f2py_rout_connectedpixels_blobproperties(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,int*,int,float,int,int,int,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *data = NULL;
  npy_intp data_Dims[2] = {-1, -1};
  const int data_Rank = 2;
  PyArrayObject *capi_data_tmp = NULL;
  int capi_data_intent = 0;
  PyObject *data_capi = Py_None;
  int *labels = NULL;
  npy_intp labels_Dims[2] = {-1, -1};
  const int labels_Rank = 2;
  PyArrayObject *capi_labels_tmp = NULL;
  int capi_labels_intent = 0;
  PyObject *labels_capi = Py_None;
  int np = 0;
  PyObject *np_capi = Py_None;
  float omega = 0;
  PyObject *omega_capi = Py_None;
  int verbose = 0;
  PyObject *verbose_capi = Py_None;
  int ns = 0;
  int nf = 0;
  double *results = NULL;
  npy_intp results_Dims[2] = {-1, -1};
  const int results_Rank = 2;
  PyArrayObject *capi_results_tmp = NULL;
  int capi_results_intent = 0;
  static char *capi_kwlist[] = {"data","labels","np","omega","verbose",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OO:connectedpixels.blobproperties",\
    capi_kwlist,&data_capi,&labels_capi,&np_capi,&omega_capi,&verbose_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable verbose */
  if (verbose_capi == Py_None) verbose = 0; else
    f2py_success = int_from_pyobj(&verbose,verbose_capi,"connectedpixels.blobproperties() 2nd keyword (verbose) can't be converted to int");
  if (f2py_success) {
  /* Processing variable data */
  ;
  capi_data_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_data_tmp = array_from_pyobj(NPY_FLOAT,data_Dims,data_Rank,capi_data_intent,data_capi);
  if (capi_data_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `data' of connectedpixels.blobproperties to C/Fortran array" );
  } else {
    data = (float *)(PyArray_DATA(capi_data_tmp));

  /* Processing variable np */
    f2py_success = int_from_pyobj(&np,np_capi,"connectedpixels.blobproperties() 3rd argument (np) can't be converted to int");
  if (f2py_success) {
  /* Processing variable omega */
  if (omega_capi == Py_None) omega = 0; else
    f2py_success = float_from_pyobj(&omega,omega_capi,"connectedpixels.blobproperties() 1st keyword (omega) can't be converted to float");
  if (f2py_success) {
  /* Processing variable results */
  results_Dims[0]=np,results_Dims[1]=(NPROPERTY);
  capi_results_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE|F2PY_INTENT_C;
  capi_results_tmp = array_from_pyobj(NPY_DOUBLE,results_Dims,results_Rank,capi_results_intent,Py_None);
  if (capi_results_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting hidden `results' of connectedpixels.blobproperties to C/Fortran array" );
  } else {
    results = (double *)(PyArray_DATA(capi_results_tmp));

  /* Processing variable nf */
  nf = shape(data,1);
  /* Processing variable ns */
  ns = shape(data,0);
  /* Processing variable labels */
  labels_Dims[0]=ns,labels_Dims[1]=nf;
  capi_labels_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_labels_tmp = array_from_pyobj(NPY_INT,labels_Dims,labels_Rank,capi_labels_intent,labels_capi);
  if (capi_labels_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `labels' of connectedpixels.blobproperties to C/Fortran array" );
  } else {
    labels = (int *)(PyArray_DATA(capi_labels_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
      Py_BEGIN_ALLOW_THREADS
        (*f2py_func)(data,labels,np,omega,verbose,ns,nf,results);
      Py_END_ALLOW_THREADS
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_results_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_labels_tmp!=labels_capi) {
    Py_XDECREF(capi_labels_tmp); }
  }  /*if (capi_labels_tmp == NULL) ... else of labels*/
  /* End of cleaning variable labels */
  /* End of cleaning variable ns */
  /* End of cleaning variable nf */
  }  /*if (capi_results_tmp == NULL) ... else of results*/
  /* End of cleaning variable results */
  } /*if (f2py_success) of omega*/
  /* End of cleaning variable omega */
  } /*if (f2py_success) of np*/
  /* End of cleaning variable np */
  if((PyObject *)capi_data_tmp!=data_capi) {
    Py_XDECREF(capi_data_tmp); }
  }  /*if (capi_data_tmp == NULL) ... else of data*/
  /* End of cleaning variable data */
  } /*if (f2py_success) of verbose*/
  /* End of cleaning variable verbose */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of blobproperties ***************************/

/******************************** blob_moments ********************************/
static char doc_f2py_rout_connectedpixels_blob_moments[] = "\
blob_moments(results)\n\nWrapper for ``blob_moments``.\
\n\nParameters\n----------\n"
"results : in/output rank-2 array('d') with bounds (np,(NPROPERTY))";
/* extern void blob_moments(double*,int); */
static PyObject *f2py_rout_connectedpixels_blob_moments(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *results = NULL;
  npy_intp results_Dims[2] = {-1, -1};
  const int results_Rank = 2;
  PyArrayObject *capi_results_tmp = NULL;
  int capi_results_intent = 0;
  PyObject *results_capi = Py_None;
  int np = 0;
  static char *capi_kwlist[] = {"results",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:connectedpixels.blob_moments",\
    capi_kwlist,&results_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable results */
  results_Dims[1]=(NPROPERTY);
  capi_results_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_results_tmp = array_from_pyobj(NPY_DOUBLE,results_Dims,results_Rank,capi_results_intent,results_capi);
  if (capi_results_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `results' of connectedpixels.blob_moments to C/Fortran array" );
  } else {
    results = (double *)(PyArray_DATA(capi_results_tmp));

  /* Processing variable np */
  np = shape(results,0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
      Py_BEGIN_ALLOW_THREADS
        (*f2py_func)(results,np);
      Py_END_ALLOW_THREADS
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable np */
  if((PyObject *)capi_results_tmp!=results_capi) {
    Py_XDECREF(capi_results_tmp); }
  }  /*if (capi_results_tmp == NULL) ... else of results*/
  /* End of cleaning variable results */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of blob_moments ****************************/

/******************************** bloboverlaps ********************************/
static char doc_f2py_rout_connectedpixels_bloboverlaps[] = "\
bloboverlaps = bloboverlaps(labels1,npk1,results1,labels2,npk2,results2,[verbose])\n\nWrapper for ``bloboverlaps``.\
\n\nParameters\n----------\n"
"labels1 : in/output rank-2 array('i') with bounds (ns,nf)\n"
"npk1 : input int\n"
"results1 : in/output rank-2 array('d') with bounds (:,(NPROPERTY))\n"
"labels2 : in/output rank-2 array('i') with bounds (ns,nf)\n"
"npk2 : input int\n"
"results2 : in/output rank-2 array('d') with bounds (:,(NPROPERTY))\n"
"\nOther Parameters\n----------------\n"
"verbose : input int, optional\n    Default: 0\n"
"\nReturns\n-------\n"
"bloboverlaps : int";
/* extern int bloboverlaps(int*,int,double*,int*,int,double*,int,int,int); */
static PyObject *f2py_rout_connectedpixels_bloboverlaps(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(int*,int,double*,int*,int,double*,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int bloboverlaps_return_value=0;
  int *labels1 = NULL;
  npy_intp labels1_Dims[2] = {-1, -1};
  const int labels1_Rank = 2;
  PyArrayObject *capi_labels1_tmp = NULL;
  int capi_labels1_intent = 0;
  PyObject *labels1_capi = Py_None;
  int npk1 = 0;
  PyObject *npk1_capi = Py_None;
  double *results1 = NULL;
  npy_intp results1_Dims[2] = {-1, -1};
  const int results1_Rank = 2;
  PyArrayObject *capi_results1_tmp = NULL;
  int capi_results1_intent = 0;
  PyObject *results1_capi = Py_None;
  int *labels2 = NULL;
  npy_intp labels2_Dims[2] = {-1, -1};
  const int labels2_Rank = 2;
  PyArrayObject *capi_labels2_tmp = NULL;
  int capi_labels2_intent = 0;
  PyObject *labels2_capi = Py_None;
  int npk2 = 0;
  PyObject *npk2_capi = Py_None;
  double *results2 = NULL;
  npy_intp results2_Dims[2] = {-1, -1};
  const int results2_Rank = 2;
  PyArrayObject *capi_results2_tmp = NULL;
  int capi_results2_intent = 0;
  PyObject *results2_capi = Py_None;
  int verbose = 0;
  PyObject *verbose_capi = Py_None;
  int ns = 0;
  int nf = 0;
  static char *capi_kwlist[] = {"labels1","npk1","results1","labels2","npk2","results2","verbose",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|O:connectedpixels.bloboverlaps",\
    capi_kwlist,&labels1_capi,&npk1_capi,&results1_capi,&labels2_capi,&npk2_capi,&results2_capi,&verbose_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable results2 */
  results2_Dims[1]=(NPROPERTY);
  capi_results2_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_results2_tmp = array_from_pyobj(NPY_DOUBLE,results2_Dims,results2_Rank,capi_results2_intent,results2_capi);
  if (capi_results2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 6th argument `results2' of connectedpixels.bloboverlaps to C/Fortran array" );
  } else {
    results2 = (double *)(PyArray_DATA(capi_results2_tmp));

  /* Processing variable verbose */
  if (verbose_capi == Py_None) verbose = 0; else
    f2py_success = int_from_pyobj(&verbose,verbose_capi,"connectedpixels.bloboverlaps() 1st keyword (verbose) can't be converted to int");
  if (f2py_success) {
  /* Processing variable results1 */
  results1_Dims[1]=(NPROPERTY);
  capi_results1_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_results1_tmp = array_from_pyobj(NPY_DOUBLE,results1_Dims,results1_Rank,capi_results1_intent,results1_capi);
  if (capi_results1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 3rd argument `results1' of connectedpixels.bloboverlaps to C/Fortran array" );
  } else {
    results1 = (double *)(PyArray_DATA(capi_results1_tmp));

  /* Processing variable labels1 */
  ;
  capi_labels1_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_labels1_tmp = array_from_pyobj(NPY_INT,labels1_Dims,labels1_Rank,capi_labels1_intent,labels1_capi);
  if (capi_labels1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `labels1' of connectedpixels.bloboverlaps to C/Fortran array" );
  } else {
    labels1 = (int *)(PyArray_DATA(capi_labels1_tmp));

  /* Processing variable npk2 */
    f2py_success = int_from_pyobj(&npk2,npk2_capi,"connectedpixels.bloboverlaps() 5th argument (npk2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable npk1 */
    f2py_success = int_from_pyobj(&npk1,npk1_capi,"connectedpixels.bloboverlaps() 2nd argument (npk1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nf */
  nf = shape(labels1,1);
  /* Processing variable ns */
  ns = shape(labels1,0);
  /* Processing variable labels2 */
  labels2_Dims[0]=ns,labels2_Dims[1]=nf;
  capi_labels2_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_labels2_tmp = array_from_pyobj(NPY_INT,labels2_Dims,labels2_Rank,capi_labels2_intent,labels2_capi);
  if (capi_labels2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 4th argument `labels2' of connectedpixels.bloboverlaps to C/Fortran array" );
  } else {
    labels2 = (int *)(PyArray_DATA(capi_labels2_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  bloboverlaps_return_value = (*f2py_func)(labels1,npk1,results1,labels2,npk2,results2,verbose,ns,nf);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",bloboverlaps_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_labels2_tmp!=labels2_capi) {
    Py_XDECREF(capi_labels2_tmp); }
  }  /*if (capi_labels2_tmp == NULL) ... else of labels2*/
  /* End of cleaning variable labels2 */
  /* End of cleaning variable ns */
  /* End of cleaning variable nf */
  } /*if (f2py_success) of npk1*/
  /* End of cleaning variable npk1 */
  } /*if (f2py_success) of npk2*/
  /* End of cleaning variable npk2 */
  if((PyObject *)capi_labels1_tmp!=labels1_capi) {
    Py_XDECREF(capi_labels1_tmp); }
  }  /*if (capi_labels1_tmp == NULL) ... else of labels1*/
  /* End of cleaning variable labels1 */
  if((PyObject *)capi_results1_tmp!=results1_capi) {
    Py_XDECREF(capi_results1_tmp); }
  }  /*if (capi_results1_tmp == NULL) ... else of results1*/
  /* End of cleaning variable results1 */
  } /*if (f2py_success) of verbose*/
  /* End of cleaning variable verbose */
  if((PyObject *)capi_results2_tmp!=results2_capi) {
    Py_XDECREF(capi_results2_tmp); }
  }  /*if (capi_results2_tmp == NULL) ... else of results2*/
  /* End of cleaning variable results2 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of bloboverlaps ****************************/

/********************************** closest **********************************/
static char doc_f2py_rout_connectedpixels_closest[] = "\
ibest,best = closest(x,v)\n\nWrapper for ``closest``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('d') with bounds (nx)\n"
"v : input rank-1 array('d') with bounds (nv)\n"
"\nReturns\n-------\n"
"ibest : int\n"
"best : float";
/* extern void closest(double*,double*,int*,double*,int,int); */
static PyObject *f2py_rout_connectedpixels_closest(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,double*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *v = NULL;
  npy_intp v_Dims[1] = {-1};
  const int v_Rank = 1;
  PyArrayObject *capi_v_tmp = NULL;
  int capi_v_intent = 0;
  PyObject *v_capi = Py_None;
  int ibest = 0;
  double best = 0;
  int nx = 0;
  int nv = 0;
  static char *capi_kwlist[] = {"x","v",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:connectedpixels.closest",\
    capi_kwlist,&x_capi,&v_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable best */
  /* Processing variable v */
  ;
  capi_v_intent |= F2PY_INTENT_IN;
  capi_v_tmp = array_from_pyobj(NPY_DOUBLE,v_Dims,v_Rank,capi_v_intent,v_capi);
  if (capi_v_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `v' of connectedpixels.closest to C/Fortran array" );
  } else {
    v = (double *)(PyArray_DATA(capi_v_tmp));

  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `x' of connectedpixels.closest to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable ibest */
  /* Processing variable nx */
  nx = shape(x,0);
  /* Processing variable nv */
  nv = shape(v,0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x,v,&ibest,&best,nx,nv);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("id",ibest,best);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable nv */
  /* End of cleaning variable nx */
  /* End of cleaning variable ibest */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  if((PyObject *)capi_v_tmp!=v_capi) {
    Py_XDECREF(capi_v_tmp); }
  }  /*if (capi_v_tmp == NULL) ... else of v*/
  /* End of cleaning variable v */
  /* End of cleaning variable best */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of closest *******************************/

/*********************************** score ***********************************/
static char doc_f2py_rout_connectedpixels_score[] = "\
score = score(ubi,gv,tol)\n\nWrapper for ``score``.\
\n\nParameters\n----------\n"
"ubi : input rank-2 array('d') with bounds (3,3)\n"
"gv : input rank-2 array('d') with bounds (ng,3)\n"
"tol : input float\n"
"\nReturns\n-------\n"
"score : int";
/* extern int score(double*,double*,double,int); */
static PyObject *f2py_rout_connectedpixels_score(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(double*,double*,double,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int score_return_value=0;
  double *ubi = NULL;
  npy_intp ubi_Dims[2] = {-1, -1};
  const int ubi_Rank = 2;
  PyArrayObject *capi_ubi_tmp = NULL;
  int capi_ubi_intent = 0;
  PyObject *ubi_capi = Py_None;
  double *gv = NULL;
  npy_intp gv_Dims[2] = {-1, -1};
  const int gv_Rank = 2;
  PyArrayObject *capi_gv_tmp = NULL;
  int capi_gv_intent = 0;
  PyObject *gv_capi = Py_None;
  double tol = 0;
  PyObject *tol_capi = Py_None;
  int ng = 0;
  static char *capi_kwlist[] = {"ubi","gv","tol",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:connectedpixels.score",\
    capi_kwlist,&ubi_capi,&gv_capi,&tol_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable gv */
  gv_Dims[1]=3;
  capi_gv_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_gv_tmp = array_from_pyobj(NPY_DOUBLE,gv_Dims,gv_Rank,capi_gv_intent,gv_capi);
  if (capi_gv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `gv' of connectedpixels.score to C/Fortran array" );
  } else {
    gv = (double *)(PyArray_DATA(capi_gv_tmp));

  /* Processing variable ubi */
  ubi_Dims[0]=3,ubi_Dims[1]=3;
  capi_ubi_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_ubi_tmp = array_from_pyobj(NPY_DOUBLE,ubi_Dims,ubi_Rank,capi_ubi_intent,ubi_capi);
  if (capi_ubi_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `ubi' of connectedpixels.score to C/Fortran array" );
  } else {
    ubi = (double *)(PyArray_DATA(capi_ubi_tmp));

  /* Processing variable tol */
    f2py_success = double_from_pyobj(&tol,tol_capi,"connectedpixels.score() 3rd argument (tol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ng */
  ng = shape(gv,0);
  CHECKSCALAR(shape(gv,0)==ng,"shape(gv,0)==ng","hidden ng","score:ng=%d",ng) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  score_return_value = (*f2py_func)(ubi,gv,tol,ng);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",score_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(gv,0)==ng)*/
  /* End of cleaning variable ng */
  } /*if (f2py_success) of tol*/
  /* End of cleaning variable tol */
  if((PyObject *)capi_ubi_tmp!=ubi_capi) {
    Py_XDECREF(capi_ubi_tmp); }
  }  /*if (capi_ubi_tmp == NULL) ... else of ubi*/
  /* End of cleaning variable ubi */
  if((PyObject *)capi_gv_tmp!=gv_capi) {
    Py_XDECREF(capi_gv_tmp); }
  }  /*if (capi_gv_tmp == NULL) ... else of gv*/
  /* End of cleaning variable gv */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of score ********************************/

/****************************** score_and_refine ******************************/
static char doc_f2py_rout_connectedpixels_score_and_refine[] = "\
n,sumdrlv2 = score_and_refine(ubi,gv,tol)\n\nWrapper for ``score_and_refine``.\
\n\nParameters\n----------\n"
"ubi : in/output rank-2 array('d') with bounds (3,3)\n"
"gv : input rank-2 array('d') with bounds (ng,3)\n"
"tol : input float\n"
"\nReturns\n-------\n"
"n : int\n"
"sumdrlv2 : float";
/* extern void score_and_refine(double*,double*,double,int*,double*,int); */
static PyObject *f2py_rout_connectedpixels_score_and_refine(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double,int*,double*,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *ubi = NULL;
  npy_intp ubi_Dims[2] = {-1, -1};
  const int ubi_Rank = 2;
  PyArrayObject *capi_ubi_tmp = NULL;
  int capi_ubi_intent = 0;
  PyObject *ubi_capi = Py_None;
  double *gv = NULL;
  npy_intp gv_Dims[2] = {-1, -1};
  const int gv_Rank = 2;
  PyArrayObject *capi_gv_tmp = NULL;
  int capi_gv_intent = 0;
  PyObject *gv_capi = Py_None;
  double tol = 0;
  PyObject *tol_capi = Py_None;
  int n = 0;
  double sumdrlv2 = 0;
  int ng = 0;
  static char *capi_kwlist[] = {"ubi","gv","tol",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:connectedpixels.score_and_refine",\
    capi_kwlist,&ubi_capi,&gv_capi,&tol_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable gv */
  gv_Dims[1]=3;
  capi_gv_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_gv_tmp = array_from_pyobj(NPY_DOUBLE,gv_Dims,gv_Rank,capi_gv_intent,gv_capi);
  if (capi_gv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `gv' of connectedpixels.score_and_refine to C/Fortran array" );
  } else {
    gv = (double *)(PyArray_DATA(capi_gv_tmp));

  /* Processing variable sumdrlv2 */
  /* Processing variable tol */
    f2py_success = double_from_pyobj(&tol,tol_capi,"connectedpixels.score_and_refine() 3rd argument (tol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable n */
  /* Processing variable ubi */
  ubi_Dims[0]=3,ubi_Dims[1]=3;
  capi_ubi_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_ubi_tmp = array_from_pyobj(NPY_DOUBLE,ubi_Dims,ubi_Rank,capi_ubi_intent,ubi_capi);
  if (capi_ubi_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `ubi' of connectedpixels.score_and_refine to C/Fortran array" );
  } else {
    ubi = (double *)(PyArray_DATA(capi_ubi_tmp));

  /* Processing variable ng */
  ng = shape(gv,0);
  CHECKSCALAR(shape(gv,0)==ng,"shape(gv,0)==ng","hidden ng","score_and_refine:ng=%d",ng) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(ubi,gv,tol,&n,&sumdrlv2,ng);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("id",n,sumdrlv2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(gv,0)==ng)*/
  /* End of cleaning variable ng */
  if((PyObject *)capi_ubi_tmp!=ubi_capi) {
    Py_XDECREF(capi_ubi_tmp); }
  }  /*if (capi_ubi_tmp == NULL) ... else of ubi*/
  /* End of cleaning variable ubi */
  /* End of cleaning variable n */
  } /*if (f2py_success) of tol*/
  /* End of cleaning variable tol */
  /* End of cleaning variable sumdrlv2 */
  if((PyObject *)capi_gv_tmp!=gv_capi) {
    Py_XDECREF(capi_gv_tmp); }
  }  /*if (capi_gv_tmp == NULL) ... else of gv*/
  /* End of cleaning variable gv */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of score_and_refine **************************/

/****************************** score_and_assign ******************************/
static char doc_f2py_rout_connectedpixels_score_and_assign[] = "\
score_and_assign = score_and_assign(ubi,gv,tol,drlv2,labels,label)\n\nWrapper for ``score_and_assign``.\
\n\nParameters\n----------\n"
"ubi : input rank-2 array('d') with bounds (3,3)\n"
"gv : input rank-2 array('d') with bounds (ng,3)\n"
"tol : input float\n"
"drlv2 : in/output rank-1 array('d') with bounds (ng)\n"
"labels : in/output rank-1 array('i') with bounds (ng)\n"
"label : input int\n"
"\nReturns\n-------\n"
"score_and_assign : int";
/* extern int score_and_assign(double*,double*,double,double*,int*,int,int); */
static PyObject *f2py_rout_connectedpixels_score_and_assign(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(double*,double*,double,double*,int*,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int score_and_assign_return_value=0;
  double *ubi = NULL;
  npy_intp ubi_Dims[2] = {-1, -1};
  const int ubi_Rank = 2;
  PyArrayObject *capi_ubi_tmp = NULL;
  int capi_ubi_intent = 0;
  PyObject *ubi_capi = Py_None;
  double *gv = NULL;
  npy_intp gv_Dims[2] = {-1, -1};
  const int gv_Rank = 2;
  PyArrayObject *capi_gv_tmp = NULL;
  int capi_gv_intent = 0;
  PyObject *gv_capi = Py_None;
  double tol = 0;
  PyObject *tol_capi = Py_None;
  double *drlv2 = NULL;
  npy_intp drlv2_Dims[1] = {-1};
  const int drlv2_Rank = 1;
  PyArrayObject *capi_drlv2_tmp = NULL;
  int capi_drlv2_intent = 0;
  PyObject *drlv2_capi = Py_None;
  int *labels = NULL;
  npy_intp labels_Dims[1] = {-1};
  const int labels_Rank = 1;
  PyArrayObject *capi_labels_tmp = NULL;
  int capi_labels_intent = 0;
  PyObject *labels_capi = Py_None;
  int label = 0;
  PyObject *label_capi = Py_None;
  int ng = 0;
  static char *capi_kwlist[] = {"ubi","gv","tol","drlv2","labels","label",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:connectedpixels.score_and_assign",\
    capi_kwlist,&ubi_capi,&gv_capi,&tol_capi,&drlv2_capi,&labels_capi,&label_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable gv */
  gv_Dims[1]=3;
  capi_gv_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_gv_tmp = array_from_pyobj(NPY_DOUBLE,gv_Dims,gv_Rank,capi_gv_intent,gv_capi);
  if (capi_gv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `gv' of connectedpixels.score_and_assign to C/Fortran array" );
  } else {
    gv = (double *)(PyArray_DATA(capi_gv_tmp));

  /* Processing variable label */
    f2py_success = int_from_pyobj(&label,label_capi,"connectedpixels.score_and_assign() 6th argument (label) can't be converted to int");
  if (f2py_success) {
  /* Processing variable tol */
    f2py_success = double_from_pyobj(&tol,tol_capi,"connectedpixels.score_and_assign() 3rd argument (tol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ubi */
  ubi_Dims[0]=3,ubi_Dims[1]=3;
  capi_ubi_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_ubi_tmp = array_from_pyobj(NPY_DOUBLE,ubi_Dims,ubi_Rank,capi_ubi_intent,ubi_capi);
  if (capi_ubi_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `ubi' of connectedpixels.score_and_assign to C/Fortran array" );
  } else {
    ubi = (double *)(PyArray_DATA(capi_ubi_tmp));

  /* Processing variable ng */
  ng = shape(gv,0);
  CHECKSCALAR(shape(gv,0)==ng,"shape(gv,0)==ng","hidden ng","score_and_assign:ng=%d",ng) {
  /* Processing variable labels */
  labels_Dims[0]=ng;
  capi_labels_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_labels_tmp = array_from_pyobj(NPY_INT,labels_Dims,labels_Rank,capi_labels_intent,labels_capi);
  if (capi_labels_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 5th argument `labels' of connectedpixels.score_and_assign to C/Fortran array" );
  } else {
    labels = (int *)(PyArray_DATA(capi_labels_tmp));

  /* Processing variable drlv2 */
  drlv2_Dims[0]=ng;
  capi_drlv2_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_drlv2_tmp = array_from_pyobj(NPY_DOUBLE,drlv2_Dims,drlv2_Rank,capi_drlv2_intent,drlv2_capi);
  if (capi_drlv2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 4th argument `drlv2' of connectedpixels.score_and_assign to C/Fortran array" );
  } else {
    drlv2 = (double *)(PyArray_DATA(capi_drlv2_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  score_and_assign_return_value = (*f2py_func)(ubi,gv,tol,drlv2,labels,label,ng);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",score_and_assign_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_drlv2_tmp!=drlv2_capi) {
    Py_XDECREF(capi_drlv2_tmp); }
  }  /*if (capi_drlv2_tmp == NULL) ... else of drlv2*/
  /* End of cleaning variable drlv2 */
  if((PyObject *)capi_labels_tmp!=labels_capi) {
    Py_XDECREF(capi_labels_tmp); }
  }  /*if (capi_labels_tmp == NULL) ... else of labels*/
  /* End of cleaning variable labels */
  } /*CHECKSCALAR(shape(gv,0)==ng)*/
  /* End of cleaning variable ng */
  if((PyObject *)capi_ubi_tmp!=ubi_capi) {
    Py_XDECREF(capi_ubi_tmp); }
  }  /*if (capi_ubi_tmp == NULL) ... else of ubi*/
  /* End of cleaning variable ubi */
  } /*if (f2py_success) of tol*/
  /* End of cleaning variable tol */
  } /*if (f2py_success) of label*/
  /* End of cleaning variable label */
  if((PyObject *)capi_gv_tmp!=gv_capi) {
    Py_XDECREF(capi_gv_tmp); }
  }  /*if (capi_gv_tmp == NULL) ... else of gv*/
  /* End of cleaning variable gv */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of score_and_assign **************************/

/****************************** refine_assigned ******************************/
static char doc_f2py_rout_connectedpixels_refine_assigned[] = "\
npk,drlv2 = refine_assigned(ubi,gv,labels,label)\n\nWrapper for ``refine_assigned``.\
\n\nParameters\n----------\n"
"ubi : input rank-2 array('d') with bounds (3,3)\n"
"gv : input rank-2 array('d') with bounds (ng,3)\n"
"labels : input rank-1 array('i') with bounds (ng)\n"
"label : input int\n"
"\nReturns\n-------\n"
"npk : int\n"
"drlv2 : float";
/* extern void refine_assigned(double*,double*,int*,int,int*,double*,int); */
static PyObject *f2py_rout_connectedpixels_refine_assigned(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int,int*,double*,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *ubi = NULL;
  npy_intp ubi_Dims[2] = {-1, -1};
  const int ubi_Rank = 2;
  PyArrayObject *capi_ubi_tmp = NULL;
  int capi_ubi_intent = 0;
  PyObject *ubi_capi = Py_None;
  double *gv = NULL;
  npy_intp gv_Dims[2] = {-1, -1};
  const int gv_Rank = 2;
  PyArrayObject *capi_gv_tmp = NULL;
  int capi_gv_intent = 0;
  PyObject *gv_capi = Py_None;
  int *labels = NULL;
  npy_intp labels_Dims[1] = {-1};
  const int labels_Rank = 1;
  PyArrayObject *capi_labels_tmp = NULL;
  int capi_labels_intent = 0;
  PyObject *labels_capi = Py_None;
  int label = 0;
  PyObject *label_capi = Py_None;
  int npk = 0;
  double drlv2 = 0;
  int ng = 0;
  static char *capi_kwlist[] = {"ubi","gv","labels","label",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:connectedpixels.refine_assigned",\
    capi_kwlist,&ubi_capi,&gv_capi,&labels_capi,&label_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable gv */
  gv_Dims[1]=3;
  capi_gv_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_gv_tmp = array_from_pyobj(NPY_DOUBLE,gv_Dims,gv_Rank,capi_gv_intent,gv_capi);
  if (capi_gv_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `gv' of connectedpixels.refine_assigned to C/Fortran array" );
  } else {
    gv = (double *)(PyArray_DATA(capi_gv_tmp));

  /* Processing variable npk */
  /* Processing variable drlv2 */
  /* Processing variable label */
    f2py_success = int_from_pyobj(&label,label_capi,"connectedpixels.refine_assigned() 4th argument (label) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ubi */
  ubi_Dims[0]=3,ubi_Dims[1]=3;
  capi_ubi_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_ubi_tmp = array_from_pyobj(NPY_DOUBLE,ubi_Dims,ubi_Rank,capi_ubi_intent,ubi_capi);
  if (capi_ubi_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `ubi' of connectedpixels.refine_assigned to C/Fortran array" );
  } else {
    ubi = (double *)(PyArray_DATA(capi_ubi_tmp));

  /* Processing variable ng */
  ng = shape(gv,0);
  CHECKSCALAR(shape(gv,0)==ng,"shape(gv,0)==ng","hidden ng","refine_assigned:ng=%d",ng) {
  /* Processing variable labels */
  labels_Dims[0]=ng;
  capi_labels_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_labels_tmp = array_from_pyobj(NPY_INT,labels_Dims,labels_Rank,capi_labels_intent,labels_capi);
  if (capi_labels_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 3rd argument `labels' of connectedpixels.refine_assigned to C/Fortran array" );
  } else {
    labels = (int *)(PyArray_DATA(capi_labels_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(ubi,gv,labels,label,&npk,&drlv2,ng);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("id",npk,drlv2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_labels_tmp!=labels_capi) {
    Py_XDECREF(capi_labels_tmp); }
  }  /*if (capi_labels_tmp == NULL) ... else of labels*/
  /* End of cleaning variable labels */
  } /*CHECKSCALAR(shape(gv,0)==ng)*/
  /* End of cleaning variable ng */
  if((PyObject *)capi_ubi_tmp!=ubi_capi) {
    Py_XDECREF(capi_ubi_tmp); }
  }  /*if (capi_ubi_tmp == NULL) ... else of ubi*/
  /* End of cleaning variable ubi */
  } /*if (f2py_success) of label*/
  /* End of cleaning variable label */
  /* End of cleaning variable drlv2 */
  /* End of cleaning variable npk */
  if((PyObject *)capi_gv_tmp!=gv_capi) {
    Py_XDECREF(capi_gv_tmp); }
  }  /*if (capi_gv_tmp == NULL) ... else of gv*/
  /* End of cleaning variable gv */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of refine_assigned ***************************/

/********************************** put_incr **********************************/
static char doc_f2py_rout_connectedpixels_put_incr[] = "\
put_incr(data,ind,vals,[boundscheck])\n\nWrapper for ``put_incr``.\
\n\nParameters\n----------\n"
"data : in/output rank-1 array('f') with bounds (m)\n"
"ind : input rank-1 array('q') with bounds (n)\n"
"vals : input rank-1 array('f') with bounds (n)\n"
"\nOther Parameters\n----------------\n"
"boundscheck : input int, optional\n    Default: 0";
/* extern void put_incr(float*,long_long*,float*,int,int,int); */
static PyObject *f2py_rout_connectedpixels_put_incr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,long_long*,float*,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *data = NULL;
  npy_intp data_Dims[1] = {-1};
  const int data_Rank = 1;
  PyArrayObject *capi_data_tmp = NULL;
  int capi_data_intent = 0;
  PyObject *data_capi = Py_None;
  long_long *ind = NULL;
  npy_intp ind_Dims[1] = {-1};
  const int ind_Rank = 1;
  PyArrayObject *capi_ind_tmp = NULL;
  int capi_ind_intent = 0;
  PyObject *ind_capi = Py_None;
  float *vals = NULL;
  npy_intp vals_Dims[1] = {-1};
  const int vals_Rank = 1;
  PyArrayObject *capi_vals_tmp = NULL;
  int capi_vals_intent = 0;
  PyObject *vals_capi = Py_None;
  int boundscheck = 0;
  PyObject *boundscheck_capi = Py_None;
  int n = 0;
  int m = 0;
  static char *capi_kwlist[] = {"data","ind","vals","boundscheck",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|O:connectedpixels.put_incr",\
    capi_kwlist,&data_capi,&ind_capi,&vals_capi,&boundscheck_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ind */
  ;
  capi_ind_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_ind_tmp = array_from_pyobj(NPY_LONGLONG,ind_Dims,ind_Rank,capi_ind_intent,ind_capi);
  if (capi_ind_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `ind' of connectedpixels.put_incr to C/Fortran array" );
  } else {
    ind = (long_long *)(PyArray_DATA(capi_ind_tmp));

  /* Processing variable boundscheck */
  if (boundscheck_capi == Py_None) boundscheck = 0; else
    f2py_success = int_from_pyobj(&boundscheck,boundscheck_capi,"connectedpixels.put_incr() 1st keyword (boundscheck) can't be converted to int");
  if (f2py_success) {
  /* Processing variable data */
  ;
  capi_data_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_data_tmp = array_from_pyobj(NPY_FLOAT,data_Dims,data_Rank,capi_data_intent,data_capi);
  if (capi_data_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `data' of connectedpixels.put_incr to C/Fortran array" );
  } else {
    data = (float *)(PyArray_DATA(capi_data_tmp));

  /* Processing variable m */
  m = len(data);
  CHECKSCALAR(len(data)>=m,"len(data)>=m","hidden m","put_incr:m=%d",m) {
  /* Processing variable n */
  n = len(ind);
  CHECKSCALAR(len(ind)>=n,"len(ind)>=n","hidden n","put_incr:n=%d",n) {
  /* Processing variable vals */
  vals_Dims[0]=n;
  capi_vals_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_vals_tmp = array_from_pyobj(NPY_FLOAT,vals_Dims,vals_Rank,capi_vals_intent,vals_capi);
  if (capi_vals_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 3rd argument `vals' of connectedpixels.put_incr to C/Fortran array" );
  } else {
    vals = (float *)(PyArray_DATA(capi_vals_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(data,ind,vals,boundscheck,n,m);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_vals_tmp!=vals_capi) {
    Py_XDECREF(capi_vals_tmp); }
  }  /*if (capi_vals_tmp == NULL) ... else of vals*/
  /* End of cleaning variable vals */
  } /*CHECKSCALAR(len(ind)>=n)*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(len(data)>=m)*/
  /* End of cleaning variable m */
  if((PyObject *)capi_data_tmp!=data_capi) {
    Py_XDECREF(capi_data_tmp); }
  }  /*if (capi_data_tmp == NULL) ... else of data*/
  /* End of cleaning variable data */
  } /*if (f2py_success) of boundscheck*/
  /* End of cleaning variable boundscheck */
  if((PyObject *)capi_ind_tmp!=ind_capi) {
    Py_XDECREF(capi_ind_tmp); }
  }  /*if (capi_ind_tmp == NULL) ... else of ind*/
  /* End of cleaning variable ind */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of put_incr ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"connectedpixels",-1,{{-1}},0,(char *)connectedpixels,(f2py_init_func)f2py_rout_connectedpixels_connectedpixels,doc_f2py_rout_connectedpixels_connectedpixels},
  {"blobproperties",-1,{{-1}},0,(char *)blobproperties,(f2py_init_func)f2py_rout_connectedpixels_blobproperties,doc_f2py_rout_connectedpixels_blobproperties},
  {"blob_moments",-1,{{-1}},0,(char *)blob_moments,(f2py_init_func)f2py_rout_connectedpixels_blob_moments,doc_f2py_rout_connectedpixels_blob_moments},
  {"bloboverlaps",-1,{{-1}},0,(char *)bloboverlaps,(f2py_init_func)f2py_rout_connectedpixels_bloboverlaps,doc_f2py_rout_connectedpixels_bloboverlaps},
  {"closest",-1,{{-1}},0,(char *)closest,(f2py_init_func)f2py_rout_connectedpixels_closest,doc_f2py_rout_connectedpixels_closest},
  {"score",-1,{{-1}},0,(char *)score,(f2py_init_func)f2py_rout_connectedpixels_score,doc_f2py_rout_connectedpixels_score},
  {"score_and_refine",-1,{{-1}},0,(char *)score_and_refine,(f2py_init_func)f2py_rout_connectedpixels_score_and_refine,doc_f2py_rout_connectedpixels_score_and_refine},
  {"score_and_assign",-1,{{-1}},0,(char *)score_and_assign,(f2py_init_func)f2py_rout_connectedpixels_score_and_assign,doc_f2py_rout_connectedpixels_score_and_assign},
  {"refine_assigned",-1,{{-1}},0,(char *)refine_assigned,(f2py_init_func)f2py_rout_connectedpixels_refine_assigned,doc_f2py_rout_connectedpixels_refine_assigned},
  {"put_incr",-1,{{-1}},0,(char *)put_incr,(f2py_init_func)f2py_rout_connectedpixels_put_incr,doc_f2py_rout_connectedpixels_put_incr},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "connectedpixels",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_connectedpixels(void) {
#else
#define RETVAL
PyMODINIT_FUNC initconnectedpixels(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = connectedpixels_module = PyModule_Create(&moduledef);
#else
  m = connectedpixels_module = Py_InitModule("connectedpixels", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module connectedpixels (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'connectedpixels' is auto-generated with f2py (version:2).\nFunctions:\n"
"  connectedpixels = connectedpixels(data,labels,threshold,verbose=0,con8=1)\n"
"  results = blobproperties(data,labels,np,omega=0,verbose=0)\n"
"  blob_moments(results)\n"
"  bloboverlaps = bloboverlaps(labels1,npk1,results1,labels2,npk2,results2,verbose=0)\n"
"  ibest,best = closest(x,v)\n"
"  score = score(ubi,gv,tol)\n"
"  n,sumdrlv2 = score_and_refine(ubi,gv,tol)\n"
"  score_and_assign = score_and_assign(ubi,gv,tol,drlv2,labels,label)\n"
"  npk,drlv2 = refine_assigned(ubi,gv,labels,label)\n"
"  put_incr(data,ind,vals,boundscheck=0)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  connectedpixels_error = PyErr_NewException ("connectedpixels.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));










/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/
  /* start usercode multiline (0) */

#define str(x) (#x)
   PyDict_SetItemString(d,str(s_1)    ,PyInt_FromLong(s_1));
   PyDict_SetItemString(d,str(s_I)    ,PyInt_FromLong(s_I));
   PyDict_SetItemString(d,str(s_I2)   ,PyInt_FromLong(s_I2));
   PyDict_SetItemString(d,str(s_fI)   ,PyInt_FromLong(s_fI));
   PyDict_SetItemString(d,str(s_ffI)  ,PyInt_FromLong(s_ffI));
   PyDict_SetItemString(d,str(s_sI)   ,PyInt_FromLong(s_sI));
   PyDict_SetItemString(d,str(s_ssI)  ,PyInt_FromLong(s_ssI));
   PyDict_SetItemString(d,str(s_sfI)  ,PyInt_FromLong(s_sfI));
   PyDict_SetItemString(d,str(s_oI)   ,PyInt_FromLong(s_oI));
   PyDict_SetItemString(d,str(s_ooI)  ,PyInt_FromLong(s_ooI));
   PyDict_SetItemString(d,str(s_soI)  ,PyInt_FromLong(s_soI));
   PyDict_SetItemString(d,str(s_foI)  ,PyInt_FromLong(s_foI));
   PyDict_SetItemString(d,str(mx_I)   ,PyInt_FromLong(mx_I));
   PyDict_SetItemString(d,str(mx_I_f) ,PyInt_FromLong(mx_I_f));
   PyDict_SetItemString(d,str(mx_I_s) ,PyInt_FromLong(mx_I_s));
   PyDict_SetItemString(d,str(mx_I_o) ,PyInt_FromLong(mx_I_o));
   PyDict_SetItemString(d,str(bb_mx_f),PyInt_FromLong(bb_mx_f));
   PyDict_SetItemString(d,str(bb_mx_s),PyInt_FromLong(bb_mx_s));
   PyDict_SetItemString(d,str(bb_mx_o),PyInt_FromLong(bb_mx_o));
   PyDict_SetItemString(d,str(bb_mn_f),PyInt_FromLong(bb_mn_f));
   PyDict_SetItemString(d,str(bb_mn_s),PyInt_FromLong(bb_mn_s));
   PyDict_SetItemString(d,str(bb_mn_o),PyInt_FromLong(bb_mn_o));

   PyDict_SetItemString(d,str(avg_i),PyInt_FromLong(avg_i));
   PyDict_SetItemString(d,str(f_raw),PyInt_FromLong(f_raw));
   PyDict_SetItemString(d,str(s_raw),PyInt_FromLong(s_raw));
   PyDict_SetItemString(d,str(f_cen),PyInt_FromLong(f_cen));
   PyDict_SetItemString(d,str(s_cen),PyInt_FromLong(s_cen));
   PyDict_SetItemString(d,str(o_raw),PyInt_FromLong(o_raw));
   PyDict_SetItemString(d,str(m_ff),PyInt_FromLong(m_ff));
   PyDict_SetItemString(d,str(m_ss),PyInt_FromLong(m_ss));
   PyDict_SetItemString(d,str(m_oo),PyInt_FromLong(m_oo));
   PyDict_SetItemString(d,str(m_sf),PyInt_FromLong(m_sf));
   PyDict_SetItemString(d,str(m_so),PyInt_FromLong(m_so));
   PyDict_SetItemString(d,str(m_fo),PyInt_FromLong(m_fo));
   PyDict_SetItemString(d,str(dety),PyInt_FromLong(dety));
   PyDict_SetItemString(d,str(detz),PyInt_FromLong(detz));
   
   PyDict_SetItemString(d,str(NPROPERTY),PyInt_FromLong(NPROPERTY));

  /* end multiline (0)*/

#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"connectedpixels");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
