/* File: connectedpixelsmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Wed Sep 20 11:29:46 2017
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *connectedpixels_error;
static PyObject *connectedpixels_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = connectedpixels_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = connectedpixels_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern int connectedpixels(float*,int*,float,int,int,int);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/****************************** connectedpixels ******************************/
static char doc_f2py_rout_connectedpixels_connectedpixels[] = "\
connectedpixels = connectedpixels(data,results,threshold,verbose)\n\nWrapper for ``connectedpixels``.\
\n\nParameters\n----------\n"
"data : input rank-2 array('f') with bounds (ns,nf)\n"
"results : in/output rank-2 array('i') with bounds (ns,nf)\n"
"threshold : input float\n"
"verbose : input int\n"
"\nReturns\n-------\n"
"connectedpixels : int";
/* extern int connectedpixels(float*,int*,float,int,int,int); */
static PyObject *f2py_rout_connectedpixels_connectedpixels(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           int (*f2py_func)(float*,int*,float,int,int,int)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int connectedpixels_return_value=0;
  float *data = NULL;
  npy_intp data_Dims[2] = {-1, -1};
  const int data_Rank = 2;
  PyArrayObject *capi_data_tmp = NULL;
  int capi_data_intent = 0;
  PyObject *data_capi = Py_None;
  int *results = NULL;
  npy_intp results_Dims[2] = {-1, -1};
  const int results_Rank = 2;
  PyArrayObject *capi_results_tmp = NULL;
  int capi_results_intent = 0;
  PyObject *results_capi = Py_None;
  float threshold = 0;
  PyObject *threshold_capi = Py_None;
  int verbose = 0;
  PyObject *verbose_capi = Py_None;
  int ns = 0;
  int nf = 0;
  static char *capi_kwlist[] = {"data","results","threshold","verbose",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:connectedpixels.connectedpixels",\
    capi_kwlist,&data_capi,&results_capi,&threshold_capi,&verbose_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable verbose */
    f2py_success = int_from_pyobj(&verbose,verbose_capi,"connectedpixels.connectedpixels() 4th argument (verbose) can't be converted to int");
  if (f2py_success) {
  /* Processing variable threshold */
    f2py_success = float_from_pyobj(&threshold,threshold_capi,"connectedpixels.connectedpixels() 3rd argument (threshold) can't be converted to float");
  if (f2py_success) {
  /* Processing variable data */
  ;
  capi_data_intent |= F2PY_INTENT_IN|F2PY_INTENT_C;
  capi_data_tmp = array_from_pyobj(NPY_FLOAT,data_Dims,data_Rank,capi_data_intent,data_capi);
  if (capi_data_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 1st argument `data' of connectedpixels.connectedpixels to C/Fortran array" );
  } else {
    data = (float *)(PyArray_DATA(capi_data_tmp));

  /* Processing variable ns */
  ns = shape(data,0);
  /* Processing variable nf */
  nf = shape(data,1);
  /* Processing variable results */
  results_Dims[0]=ns,results_Dims[1]=nf;
  capi_results_intent |= F2PY_INTENT_INOUT|F2PY_INTENT_C;
  capi_results_tmp = array_from_pyobj(NPY_INT,results_Dims,results_Rank,capi_results_intent,results_capi);
  if (capi_results_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(connectedpixels_error,"failed in converting 2nd argument `results' of connectedpixels.connectedpixels to C/Fortran array" );
  } else {
    results = (int *)(PyArray_DATA(capi_results_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  Py_BEGIN_ALLOW_THREADS
  connectedpixels_return_value = (*f2py_func)(data,results,threshold,verbose,ns,nf);
  Py_END_ALLOW_THREADS
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",connectedpixels_return_value);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_results_tmp!=results_capi) {
    Py_XDECREF(capi_results_tmp); }
  }  /*if (capi_results_tmp == NULL) ... else of results*/
  /* End of cleaning variable results */
  /* End of cleaning variable nf */
  /* End of cleaning variable ns */
  if((PyObject *)capi_data_tmp!=data_capi) {
    Py_XDECREF(capi_data_tmp); }
  }  /*if (capi_data_tmp == NULL) ... else of data*/
  /* End of cleaning variable data */
  } /*if (f2py_success) of threshold*/
  /* End of cleaning variable threshold */
  } /*if (f2py_success) of verbose*/
  /* End of cleaning variable verbose */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of connectedpixels ***************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"connectedpixels",-1,{{-1}},0,(char *)connectedpixels,(f2py_init_func)f2py_rout_connectedpixels_connectedpixels,doc_f2py_rout_connectedpixels_connectedpixels},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "connectedpixels",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_connectedpixels(void) {
#else
#define RETVAL
PyMODINIT_FUNC initconnectedpixels(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = connectedpixels_module = PyModule_Create(&moduledef);
#else
  m = connectedpixels_module = Py_InitModule("connectedpixels", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module connectedpixels (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'connectedpixels' is auto-generated with f2py (version:2).\nFunctions:\n"
"  connectedpixels = connectedpixels(data,results,threshold,verbose)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  connectedpixels_error = PyErr_NewException ("connectedpixels.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"connectedpixels");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
